from typing import TextIO

from cssbeautifier.css.options import BeautifierOptions

def default_options() -> BeautifierOptions: ...
def beautify(string: str, opts: BeautifierOptions | None = ...) -> str: ...
def beautify_file(file_name: str, opts: BeautifierOptions | None = ...): ...
def usage(stream: TextIO = ...) -> int: ...
def main() -> int: ...
