title: DOC-001 Application Requirements Specification
author: John Doe
body:
  - id: REQ-001
    specification: The application shall have a GUI
    rationale: So that the user can operate it
  - id: REQ-002
    specification: The GUI shall display the current state of the application
    rationale: So that the user can see the current state of the application
  - id: REQ-011
    specification: >
      The application shall program the connected board to the latest software version
    rationale: Older versions are no longer supported
    parent: REQ-00001-142
  - id: REQ-012
    specification: The application shall preserve board settings while programming
    rationale: So that settings are not lost
  - id: REQ-013
    specification: >
      The application shall verify the correct software version after programming
    rationale: So that the user can be sure that the board is programmed correctly
  - id: REQ-021
    specification: >
      The application shall produce audible alerts when user interaction is required
    rationale: So that users are aware
    parent: REQ-00598-589
    obsolete: true
    obsolete_reason: Users are aware but also annoyed
